version: '3'

services:
  analyzer-service:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    ports:
      - "5000:5000"
    environment:
      - FORTNITE_API_KEY=${FORTNITE_API_KEY}
    volumes:
      - ./output:/app/output
    networks:
      - fortnite-net

  prediction-service:
    build:
      context: .
      dockerfile: Dockerfile.prediction
    ports:
      - "5001:5001"
    volumes:
      - ./output:/app/output
    networks:
      - fortnite-net
    depends_on:
      - analyzer-service

networks:
  fortnite-net: 